window.FINANCE_KING_DATA = {
  "source": {
    "type": "excel",
    "name": "第一届谁是理财王_参赛选手填报模板V2.xlsx",
    "updatedAt": "2026-06-01T22:47:45"
  },
  "players": [
    {
      "id": "大哥",
      "name": "大哥",
      "initial": 100000.0,
      "current": 98951.71,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "潜伏锂矿，找准时机买PCB",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "大爷",
      "name": "大爷",
      "initial": 100000.0,
      "current": 103462.0,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "PCB！光！",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "师兄",
      "name": "师兄",
      "initial": 114574.46,
      "current": 109220.74,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "鱿鱼",
      "name": "鱿鱼",
      "initial": 100000.0,
      "current": 100000.0,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "创业板+有色+一点红利",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "老齐",
      "name": "老齐",
      "initial": 100764.46,
      "current": 102834.78,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "第一周观望为主，第二周见机行事",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "周鸟",
      "name": "周鸟",
      "initial": 106052.19,
      "current": 105899.81,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "多做善事，多结善缘",
      "profile": "基金经理介绍（可选）"
    },
    {
      "id": "男模",
      "name": "男模",
      "initial": 132725.5,
      "current": 132681.01,
      "cleanStart": false,
      "hasReport": true,
      "strategy": "存储准备跑",
      "profile": "基金经理介绍（可选）"
    }
  ],
  "trades": [
    {
      "id": "大哥-1",
      "playerId": "大哥",
      "type": "持仓快照",
      "symbol": "科创50ETF",
      "price": 3688.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 3688.0,
      "pnl": 1.0
    },
    {
      "id": "大哥-2",
      "playerId": "大哥",
      "type": "持仓快照",
      "symbol": "三安光电",
      "price": 7820.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 7820.0,
      "pnl": 1.0
    },
    {
      "id": "大哥-3",
      "playerId": "大哥",
      "type": "持仓快照",
      "symbol": "西藏矿业",
      "price": 20699.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 20699.0,
      "pnl": 1.0
    },
    {
      "id": "大哥-4",
      "playerId": "大哥",
      "type": "持仓快照",
      "symbol": "现金",
      "price": 66744.71,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "现金",
      "rmbValue": 66744.71,
      "pnl": 1.0
    },
    {
      "id": "大爷-1",
      "playerId": "大爷",
      "type": "持仓快照",
      "symbol": "沪电股份",
      "price": 26672.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 26672.0,
      "pnl": 1.0
    },
    {
      "id": "大爷-2",
      "playerId": "大爷",
      "type": "持仓快照",
      "symbol": "深南科技",
      "price": 41950.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 41950.0,
      "pnl": 1.0
    },
    {
      "id": "大爷-3",
      "playerId": "大爷",
      "type": "持仓快照",
      "symbol": "西藏矿业",
      "price": 0.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 0.0,
      "pnl": 1.0
    },
    {
      "id": "大爷-4",
      "playerId": "大爷",
      "type": "持仓快照",
      "symbol": "现金",
      "price": 20055.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "现金",
      "rmbValue": 20055.0,
      "pnl": 1.0
    },
    {
      "id": "师兄-1",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "USD",
      "price": 16874.0,
      "quantity": 1,
      "date": "2026-05-26",
      "category": "cash",
      "rmbValue": 16874.0,
      "pnl": 0.0
    },
    {
      "id": "师兄-2",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "ALRIB",
      "price": 7880.0,
      "quantity": 1,
      "date": "2026-05-27",
      "category": "股票",
      "rmbValue": 7880.0,
      "pnl": 0.0
    },
    {
      "id": "师兄-3",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "NOK",
      "price": 9660.0,
      "quantity": 1,
      "date": "2026-05-27",
      "category": "股票",
      "rmbValue": 9660.0,
      "pnl": 0.0
    },
    {
      "id": "师兄-4",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "SIVE",
      "price": 7770.0,
      "quantity": 1,
      "date": "2026-05-27",
      "category": "股票",
      "rmbValue": 7770.0,
      "pnl": 0.0
    },
    {
      "id": "师兄-5",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "ALRIB",
      "price": 7910.0,
      "quantity": 1,
      "date": "2026-05-31",
      "category": "股票",
      "rmbValue": 7910.0,
      "pnl": 7.89
    },
    {
      "id": "师兄-6",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "NOK",
      "price": 8952.0,
      "quantity": 1,
      "date": "2026-05-31",
      "category": "股票",
      "rmbValue": 8952.0,
      "pnl": 6.77
    },
    {
      "id": "师兄-7",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "SIVE",
      "price": 6700.0,
      "quantity": 1,
      "date": "2026-05-31",
      "category": "股票",
      "rmbValue": 6700.0,
      "pnl": 0.73
    },
    {
      "id": "师兄-8",
      "playerId": "师兄",
      "type": "持仓快照",
      "symbol": "债务",
      "price": -2760.0,
      "quantity": 1,
      "date": "2026-05-31",
      "category": "债务",
      "rmbValue": -2760.0,
      "pnl": 6.77
    },
    {
      "id": "鱿鱼-1",
      "playerId": "鱿鱼",
      "type": "持仓快照",
      "symbol": "创业板指",
      "price": 50000.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 50000.0,
      "pnl": 1.0
    },
    {
      "id": "鱿鱼-2",
      "playerId": "鱿鱼",
      "type": "持仓快照",
      "symbol": "有色",
      "price": 30000.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "A股",
      "rmbValue": 30000.0,
      "pnl": 1.0
    },
    {
      "id": "鱿鱼-3",
      "playerId": "鱿鱼",
      "type": "持仓快照",
      "symbol": "煤炭",
      "price": 20000.0,
      "quantity": 1,
      "date": "2026-05-27",
      "category": "A股",
      "rmbValue": 20000.0,
      "pnl": 1.0
    },
    {
      "id": "老齐-1",
      "playerId": "老齐",
      "type": "持仓快照",
      "symbol": "'002916 深南电路",
      "price": 1233.84,
      "quantity": 1,
      "date": "2026-05-26",
      "category": "A股",
      "rmbValue": 1233.84,
      "pnl": 1.0
    },
    {
      "id": "老齐-2",
      "playerId": "老齐",
      "type": "持仓快照",
      "symbol": "两倍英伟达，美光，dram",
      "price": 7242.92,
      "quantity": 1,
      "date": "2026-06-01",
      "category": "美股",
      "rmbValue": 7242.92,
      "pnl": 6.7637
    },
    {
      "id": "老齐-3",
      "playerId": "老齐",
      "type": "持仓快照",
      "symbol": "沪电股份",
      "price": 39612.0,
      "quantity": 1,
      "date": "2026-06-01",
      "category": "A股",
      "rmbValue": 39612.0,
      "pnl": 1.0
    },
    {
      "id": "老齐-4",
      "playerId": "老齐",
      "type": "持仓快照",
      "symbol": "现金",
      "price": 13000.0,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "现金",
      "rmbValue": 13000.0,
      "pnl": 1.0
    },
    {
      "id": "周鸟-1",
      "playerId": "周鸟",
      "type": "持仓快照",
      "symbol": "现金",
      "price": 63966.45,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "H股",
      "rmbValue": 63966.45,
      "pnl": 0.8658
    },
    {
      "id": "周鸟-2",
      "playerId": "周鸟",
      "type": "持仓快照",
      "symbol": "现金",
      "price": 58523.95,
      "quantity": 1,
      "date": "2026-05-25",
      "category": "H股",
      "rmbValue": 58523.95,
      "pnl": 0.8658
    },
    {
      "id": "周鸟-3",
      "playerId": "周鸟",
      "type": "持仓快照",
      "symbol": "创想三维打新",
      "price": -88.0,
      "quantity": 1,
      "date": "2026-05-28",
      "category": "H股",
      "rmbValue": -88.0,
      "pnl": 0.8658
    },
    {
      "id": "周鸟-4",
      "playerId": "周鸟",
      "type": "持仓快照",
      "symbol": "天辰生物打新",
      "price": -88.0,
      "quantity": 1,
      "date": "2026-06-01",
      "category": "H股",
      "rmbValue": -88.0,
      "pnl": 0.8658
    },
    {
      "id": "男模-1",
      "playerId": "男模",
      "type": "持仓快照",
      "symbol": "德明利",
      "price": 65910.0,
      "quantity": 1,
      "date": "2026-05-26",
      "category": "A股",
      "rmbValue": 65910.0,
      "pnl": 1.0
    },
    {
      "id": "男模-2",
      "playerId": "男模",
      "type": "持仓快照",
      "symbol": "奥比中光",
      "price": 34980.01,
      "quantity": 1,
      "date": "2026-05-26",
      "category": "A股",
      "rmbValue": 34980.01,
      "pnl": 1.0
    },
    {
      "id": "男模-3",
      "playerId": "男模",
      "type": "持仓快照",
      "symbol": "智微智能",
      "price": 31791.0,
      "quantity": 1,
      "date": "2026-05-26",
      "category": "A股",
      "rmbValue": 31791.0,
      "pnl": 1.0
    }
  ]
};
